entryPoints:
  web:
    address: ":80"
  # websecure:
  #   address: ":443"

accessLog:
  filePath: "/dev/stdout"
  bufferingSize: 0  # Disable buffering to write logs immediately

providers:
  file:
    filename: /etc/traefik/dynamic_conf.yml

http:
  routers:
    to-datadog:
      rule: "Host(`browser-intake-datadoghq.com`)"
      service: "datadog-service"
      entryPoints:
        - "websecure"
      tls:
        certResolver: "myresolver"

  services:
    datadog-service:
      loadBalancer:
        servers:
          - url: "https://browser-intake-datadoghq.com:443"

# tls:
#   certificates:
#     - certFile: /path/to/cert.crt
#       keyFile: /path/to/cert.key
#   options:
#     default:
#       minVersion: VersionTLS12

# certificatesResolvers:
#   myresolver:
#     acme:
#       email: your-email@example.com
#       storage: acme.json
#       httpChallenge:
#         entryPoint: web