entryPoints:
  web:
    address: ":80"
  # websecure:
  #   address: ":443"

accessLog:
  filePath: "/dev/stdout"
  bufferingSize: 0  # Disable buffering to write logs immediately
  fields:
    defaultMode: "keep"
    headers:
      defaultMode: "keep"
      names:
        OriginStatus: "keep"

http:
  routers:
    to-datadog:
      rule: "Host(`browser-intake-datadoghq.com`)"
      service: "datadog-service"
      entryPoints:
        - "websecure"


  services:
    datadog-service:
      loadBalancer:
        servers:
          - url: "https://browser-intake-datadoghq.com:443"

# tls:
#   certificates:
#     - certFile: /path/to/cert.crt
#       keyFile: /path/to/cert.key
#   options:
#     default:
#       minVersion: VersionTLS12

# certificatesResolvers:
#   myresolver:
#     acme:
#       email: your-email@example.com
#       storage: acme.json
#       httpChallenge:
#         entryPoint: web